using Content.Client.CrewAssignments.UI;
using Content.Shared.Access;
using Content.Shared.Access.Systems;
using Content.Shared.CCVar;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Prototypes;
using System.Linq;
using static Content.Shared.Access.Components.IdCardConsoleComponent;
using static Content.Shared.GridControl.Components.GridControlConsoleComponent;
using Content.Shared.GridControl.Components;

namespace Content.Client.GridControl.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class GridControlConsoleWindow : DefaultWindow
    {
        [Dependency] private readonly IConfigurationManager _cfgManager = default!;
        [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
        [Dependency] private readonly ILogManager _logManager = default!;
        private readonly ISawmill _logMill = default!;

        private readonly GridControlConsoleBoundUserInterface _owner;

        public GridControlConsoleWindow(GridControlConsoleBoundUserInterface owner, IPrototypeManager prototypeManager)
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
            _logMill = _logManager.GetSawmill(SharedIdCardConsoleSystem.Sawmill);

            _owner = owner;

            OnButton.OnPressed += _ => On();
            OffButton.OnPressed += _ => Off();
        }

        public void UpdateState(GridControlConsoleBoundUserInterfaceState state)
        {
            if(state.Active)
            {
                OnButton.Disabled = true;
                OffButton.Disabled = false;
            }
            else
            {
                OnButton.Disabled = false;
                OffButton.Disabled = true;
            }
        }

        public void On()
        {
            _owner.SendMessage(new GridControlConsoleComponent.GridControlOn());
        }
        public void Off()
        {
            _owner.SendMessage(new GridControlConsoleComponent.GridControlOff());
        }

    }
}
