using System.Linq;
using Content.Shared.Access;
using Content.Shared.Access.Systems;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using static Content.Shared.GridControl.Components.GridConfigComponent;
using static Robust.Client.UserInterface.Controls.BaseButton;

namespace Content.Client.GridControl.UI;
[GenerateTypedNameReferences]
public sealed partial class GridConfigWindow : DefaultWindow
{
    public GridConfigBoundUserInterface? BUI;
    public void OnGridName(ButtonEventArgs args)
    {
        if(GridNameLineEdit.Text != null && GridNameLineEdit.Text != "")
        {
            if (BUI != null)
            {
                BUI.SendMessage(new GridConfigChangeName(GridNameLineEdit.Text));
            }
        }
    }
    public void OnGridDisconnect(ButtonEventArgs args)
    {
        if (BUI != null)
        {
            BUI.SendMessage(new GridConfigDisconnect());
        }
    }

    public void OnGridConnect(ButtonEventArgs args)
    {
        if (BUI != null)
        {
            BUI.SendMessage(new GridConfigConnect());
        }
    }
    public void ChangeMode(ButtonEventArgs args)
    {
        if (BUI != null)
        {
            BUI.SendMessage(new GridConfigChangeMode());
        }
    }
    public GridConfigWindow()
    {
        RobustXamlLoader.Load(this);
        ChangeModeBtn.OnPressed += ChangeMode;

        PossibleTargets.OnItemSelected += OnTargetSelected;
        GridConnect.OnPressed += OnGridConnect;
        GridDisconnect.OnPressed += OnGridDisconnect;
        GridNameBtn.OnPressed += OnGridName;

    }
    private void OnTargetSelected(OptionButton.ItemSelectedEventArgs args)
    {
        if (BUI != null)
        {
            BUI.SendMessage(new GridConfigTargetSelect(args.Id));
        }
    }
    public void UpdateState(IPrototypeManager protoManager, GridConfigBoundUserInterfaceState state)
    {
        if(state.IdPresent)
        {
            PrivilegedIdButton.Text = state.IdName;
        }
        else
        {
            PrivilegedIdButton.Text = "";
        }
        string targetName = "";
        if(state.TargetName != null)
        {
            targetName = state.TargetName; 
        }
        GridTileCount.Text = state.GridTileCount.ToString();
        if (state.PersonalMode)
        {
            ChangeModeBtn.Text = "Station";
            PossibleTargets.Visible = false;
            TargetNameLabel.Text = $"Target Person: {targetName}";

            MaxPersonalClaimTileCountContainer.Visible = true;
            MaxPersonalClaimTileCount.Text = state.MaxPersonalClaimTileCount.ToString();
        }
        else
        {
            TargetNameLabel.Text = "Target Station: ";
            ChangeModeBtn.Text = "Personal";
            PossibleTargets.Clear();
            PossibleTargets.Visible = true;
            PossibleTargets.AddItem("None", 0);
            if (state.PossibleStations != null)
            {
                foreach (var kv in state.PossibleStations)
                {
                    PossibleTargets.AddItem(kv.Value, kv.Key);
                    if (kv.Key == state.targetStation)
                    {
                        PossibleTargets.SelectId(kv.Key);
                    }
                }
            }
            MaxPersonalClaimTileCountContainer.Visible = false;
        }
        bool gridFound = false;
        if(state.GridName != null)
        {
            gridFound = true;
            GridNameLabel.Text = state.GridName;
        }
        else
        {
            GridNameLabel.Text = "*Invalid*";
        }
        bool gridOwned = false;
        if (state.OwnerName != null)
        {
            gridOwned = true;
            GridOwnerLabel.Text = state.OwnerName;
        }
        else
        {
            GridOwnerLabel.Text = "UNCLAIMED";
        }
        if(!gridFound)
        {
            MissingPrivilegesLabel.Text = "No grid detected.";
        }
        else if(!state.IsAuth)
        {
            MissingPrivilegesLabel.Text = "You are not authorized to modify this grid.";
        }
        else
        {
            MissingPrivilegesLabel.Text = " ";
        }
        if (gridFound && state.IsAuth)
        {
            if (gridOwned)
            {
                GridConnect.Disabled = true;
                GridDisconnect.Disabled = false;
            }
            else
            {
                GridConnect.Disabled = false;
                GridDisconnect.Disabled = true;
            }
        }
        else
        {
            GridConnect.Disabled = true;
            GridDisconnect.Disabled = true;
        }
    }

}
