using System.Linq;
using Content.Shared.Access;
using Content.Shared.Access.Systems;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using static Content.Shared.GridControl.Components.StationCreatorComponent;
using static Robust.Client.UserInterface.Controls.BaseButton;

namespace Content.Client.GridControl.UISC;
[GenerateTypedNameReferences]
public sealed partial class StationCreatorWindow : DefaultWindow
{
    public StationCreatorBoundUserInterface? BUI;
    public void Finish(ButtonEventArgs args)
    {
        if (StationNameLineEdit.Text == "" || StationNameLineEdit.Text == null) return;
        if (BUI != null)
        {
            BUI.SendMessage(new StationCreatorFinish(StationNameLineEdit.Text));
        }
    }
    public StationCreatorWindow()
    {
        RobustXamlLoader.Load(this);
        FinishBtn.OnPressed += Finish;

    }
    public void UpdateState(IPrototypeManager protoManager, StationCreatorBoundUserInterfaceState state)
    {
        if (state.IdPresent)
        {
            PrivilegedIdButton.Text = state.IdName;
        }
        else
        {
            PrivilegedIdButton.Text = "";
        }
        if(state.RealName != null)
        {
            OwnerLabel.Text = state.RealName;
            FinishBtn.Disabled = false;
        }
        else
        {
            OwnerLabel.Text = "*None*";
            FinishBtn.Disabled = true;
        }

    }

}
