using Content.Client.Actions;
using Content.Client.Message;
using Content.Shared.CrewAssignments;
using Content.Shared.FixedPoint;
using Content.Shared.Store;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using System.Linq;
using System.Text;
using static Robust.Client.UserInterface.Controls.BaseButton;

namespace Content.Client.CrewAssignments.UI;

[GenerateTypedNameReferences]
public sealed partial class JobNetMenu : DefaultWindow
{
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    public event Action<ButtonEventArgs>? OnJobPressed;
    public JobNetMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

    }

    public void UpdateState(JobNetUpdateState state)
    {
        PossibleJobs.Clear();
        PossibleJobs.AddItem("Off Duty", 0);
        if(state.Stations != null)
        {
            int ind = 1;
            foreach (var kv in state.Stations)
            {

                PossibleJobs.AddItem(kv.Value, kv.Key);
                if(kv.Key == state.SelectedStation)
                    PossibleJobs.Select(ind);
                ind++;
            }
        }
        if (state.AssignmentName != null)
        {
            CSLabel.Text = state.AssignmentName;
            AssignmentDetails.Visible = true;
        }
        else
        {
            CSLabel.Text = "Off Duty";
            AssignmentDetails.Visible = false;
        }
        if (state.Wage != null)
        {
            WageLabel.Text = "$" + state.Wage.ToString();
        }
        else
        {
            WageLabel.Text = "$0";
        }
        if(state.RemainingMinutes != null)
        {
            var remainingMinutes = TimeSpan.FromMinutes(Math.Round(state.RemainingMinutes.Value.TotalMinutes));
            if(remainingMinutes <= TimeSpan.Zero)
                TimeLabel.Text = "Less than a minute!";
            else
                TimeLabel.Text = TimeSpan.FromMinutes(Math.Round(state.RemainingMinutes.Value.TotalMinutes)).ToString() + " minutes.";
        }
        else
        {
            TimeLabel.Text = "Invalid";
        }
    }



}
public sealed class JobButton : Button
{
    public int Id;
}
