using Content.Client.Cargo.Systems;
using Content.Client.Cargo.UI;
using Content.Client.Message;
using Content.Client.UserInterface.Controls;
using Content.Shared.Cargo;
using Content.Shared.Cargo.Components;
using Content.Shared.Cargo.Prototypes;
using Content.Shared.CrewAccesses.Components;
using Content.Shared.CrewAssignments.Components;
using Content.Shared.CrewAssignments.Prototypes;
using Content.Shared.Radio;
using Content.Shared.Station.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using System.Linq;
using static Robust.Client.UserInterface.Controls.BaseButton;

namespace Content.Client.CrewAssignments.UI
{

    [GenerateTypedNameReferences]
    public sealed partial class StationModificationMenu : FancyWindow
    {
        [Dependency] private readonly IGameTiming _timing = default!;

        private readonly IEntityManager _entityManager;
        private readonly IPrototypeManager _protoManager;
        private readonly CargoSystem _cargoSystem;
        private readonly SpriteSystem _spriteSystem;
        private EntityUid _owner;
        private EntityUid? _station;
        private int? _lastAssignmentSelected;
        private int? _lastChannelSelected;
        Dictionary<string, CrewAccess>? _accesses;
        Dictionary<int, CrewAssignment>? _assignments;
        public Dictionary<ProtoId<RadioChannelPrototype>, FactionRadioData>? RadioData;


        public event Action<ButtonEventArgs>? OnOwnerPressed;
        public event Action<ButtonToggledEventArgs>? OnAssignmentAccessPressed;
        public event Action<ButtonToggledEventArgs>? OnChannelAccessPressed;
        public StationModificationMenu(EntityUid owner, IEntityManager entMan, IPrototypeManager protoManager, SpriteSystem spriteSystem)
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
            _entityManager = entMan;
            _protoManager = protoManager;
            _cargoSystem = entMan.System<CargoSystem>();
            _spriteSystem = spriteSystem;
            _owner = owner;

            Title = entMan.GetComponent<MetaDataComponent>(owner).EntityName;
            TabContainer.SetTabTitle(0, "General");
            TabContainer.SetTabTitle(1, "Assignments");
            TabContainer.SetTabTitle(2, "Radio");
            TabContainer.SetTabTitle(3, "Upgrade");
            PossibleAccesses.OnItemSelected += OnDelAccessSelected;
            PossibleAssignments.OnItemSelected += OnAssignmentSelected;
            PossibleChannels.OnItemSelected += OnChannelSelected;

        }
        private void OnChannelSelected(OptionButton.ItemSelectedEventArgs args)
        {
            _lastChannelSelected = args.Id;
            PossibleChannels.SelectId(args.Id);
            UpdateChannel();

        }
        private void OnDelAccessSelected(OptionButton.ItemSelectedEventArgs args)
        {
            PossibleAccesses.SelectId(args.Id);

        }
        private void OnAssignmentSelected(OptionButton.ItemSelectedEventArgs args)
        {
            _lastAssignmentSelected = args.Id;
            PossibleAssignments.SelectId(args.Id);
            UpdateAssignment();

        }
        public void UpdateStation(EntityUid station, string name)
        {
            
            _station = station;
            StationNameLabel.Text = name;
            StationNameField.Text = name;
        }
        public void UpdateOwners(List<string> owners)
        {
            Requests.RemoveAllChildren();
            foreach (var owner in owners )
            {
                var button = new StationOwnerButton(owner);
                button.OnPressed += (args) => { OnOwnerPressed?.Invoke(args); };
                Requests.AddChild(button);
            }
        }

        public void UpdateChannels(Dictionary<ProtoId<RadioChannelPrototype>, FactionRadioData> radioData)
        {
            RadioData = radioData;
            PossibleChannels.Clear();
            foreach (var owner in radioData)
            {
                _protoManager.Resolve(owner.Key, out var radioProto);
                if (radioProto == null) continue;
                PossibleChannels.AddItem(radioProto.LocalizedName);
            }
            if (_lastChannelSelected != null)
            {
                PossibleChannels.TrySelectId(_lastChannelSelected.Value);
            }
            UpdateChannel();
        }

        public void UpdateChannel()
        {
            int id = PossibleChannels.SelectedId;
            if (RadioData == null) return;
            if (RadioData.Count-1 < id) return;
            var kv = RadioData.ElementAt(id);
            var data = kv.Value;
            ChannelEnable.Pressed = data.Enabled;
            ChannelDisable.Pressed = !data.Enabled;
            foreach (Button button in ChannelAccessesBC.Children)
            {
                if (button.Text == null) continue;
                if (data.Access.Contains(button.Text))
                {
                    button.Pressed = true;
                }
                else
                {
                    button.Pressed = false;
                }
            }
        }


        public void UpdateAccesses(Dictionary<string, CrewAccess> accesses)
        {
            _accesses = accesses;
            AssignmentAccessesBC.RemoveAllChildren();
            ChannelAccessesBC.RemoveAllChildren();
            PossibleAccesses.Clear();
            foreach (var owner in accesses)
            {
                var button = new AssignmentAccessButton(owner.Key);
                button.ToggleMode = true;
                button.OnToggled += (args) => { OnAssignmentAccessPressed?.Invoke(args); };
                button.VerticalExpand = false;
                button.HorizontalExpand = false;
                AssignmentAccessesBC.AddChild(button);
                Button button2 = new Button();
                button2.Text = owner.Key;
                button2.ToggleMode = true;
                button2.OnToggled += (args) => { OnChannelAccessPressed?.Invoke(args); };
                button2.VerticalExpand = false;
                button2.HorizontalExpand = false;
                ChannelAccessesBC.AddChild(button2);
                PossibleAccesses.AddItem(owner.Key);
            }

        }
        
        public void UpdateUpgrades(ProtoId<FactionLevelPrototype> level, int balance)
        {
            _protoManager.Resolve(level, out var levelProto);
            if (levelProto == null) return;
            FactionLevelPrototype? nextLevelProto = null;

            if(levelProto.Next != string.Empty)
                _protoManager.Resolve(levelProto.Next, out nextLevelProto);

            CurrentFactionLevelLabel.Text = levelProto.Name;
            string levelDesc = $"Owned Tile Limit:[color=yellow]{levelProto.TileLimit}[/color]";
            if (levelProto.TradestationClaim)
                levelDesc += $"\n[color=green]Can claim trade stations[/color]";
            CurrentBenefitsLabel.SetMarkup(levelDesc);
            string nextLevelDesc;
            if (nextLevelProto == null)
            {
                NextFactionLevelLabel.Text = "Max Level Attained";
                nextLevelDesc = "[color=green]Maximum Level Attained[/color]";
                LevelPurchaseButton.Visible = false;
            }
            else
            {
                NextFactionLevelLabel.Text = nextLevelProto.Name;
                nextLevelDesc = $"Owned Tile Limit:[color=green]{nextLevelProto.TileLimit}[/color]";
                if(nextLevelProto.TradestationClaim)
                {
                    nextLevelDesc += $"\n[color=green]Can claim trade stations[/color]";
                }
                LevelPurchaseButton.Visible = true;
                LevelPurchaseButton.Text = $"${nextLevelProto.Cost}";
            }
            NextBenefitsLabel.SetMarkup(nextLevelDesc);
            AccountBalanceLabel.Text = $"${balance}";

        }

        public void UpdateAssignments(Dictionary<int, CrewAssignment> assignments)
        {
            _assignments = assignments;
            PossibleAssignments.Clear();
            foreach (var owner in assignments)
            {
                PossibleAssignments.AddItem(owner.Value.Name, owner.Key);
            }
            if(_lastAssignmentSelected != null)
            {
                PossibleAssignments.TrySelectId(_lastAssignmentSelected.Value);
            }
            UpdateAssignment();
        }
        public void UpdateAssignment()
        {
            int id = PossibleAssignments.SelectedId;
            if (_assignments == null) return;
            if(_assignments.TryGetValue(id, out var assignment))
            {
                AssignmentDetails.Visible = true;
                AssignmentNameField.Text = assignment.Name;
                WageSpinBox.Value = assignment.Wage;
                CLevelSpinBox.Value = assignment.Clevel;
                if(assignment.CanClaim)
                {
                    ClaimBtn.Pressed = true;
                }
                else
                {
                    ClaimBtn.Pressed = false;
                }
                if (assignment.CanAssign)
                {
                    ReassignmentBtn.Pressed = true;
                }
                else
                {
                    ReassignmentBtn.Pressed = false;
                }
                if (assignment.CanSpend)
                {
                    SpendingBtn.Pressed = true;
                }
                else
                {
                    SpendingBtn.Pressed = false;
                }
                foreach (Button button in AssignmentAccessesBC.Children)
                {
                    if (button.Text == null) continue;
                    if (assignment.AccessIDs.Contains(button.Text))
                    {
                        button.Pressed = true;
                    }
                    else
                    {
                        button.Pressed = false;
                    }
                }
            }
            else
            {
                AssignmentDetails.Visible = false;
                AssignmentNameField.Text = "";
                WageSpinBox.Value = 0;
                CLevelSpinBox.Value = 0;
                foreach (Button button in AssignmentAccessesBC.Children)
                {
                    button.Pressed = false;
                }
            }
        }
    }
}

public sealed partial class AssignmentAccessButton : Button
{
    public string Owner { get; set; } = "";

    public AssignmentAccessButton(string owner)
    {
        Owner = owner;
        Text = owner;
    }
}
