using Content.Shared.Cargo;
using Content.Shared.Cargo.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.CrewAssignments.UI
{
    public sealed partial class StationOwnerButton : Button
    {
        public string Owner { get; set; } = "";

        public StationOwnerButton(string owner)
        {
            Owner = owner;
            Text = owner;
        }
    }
}
