using Content.Client.Message;
using Content.Shared.Cargo;
using Content.Shared.Cargo.Prototypes;
using Content.Shared.Random;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client.CrewAssignments.UI;

[GenerateTypedNameReferences]
public sealed partial class WorldObjectiveEdit : BoxContainer
{

    public int Id;

    public WorldObjectiveEdit(int id, string title, string desc, string? reward = null, DateTime? completedTime = null, string? completedDesc = null)
    {
        Id = id;
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        TitleLabel.Text = title;
        DescriptionLabel.TextRope = new Rope.Leaf(desc);
        if(completedTime == null)
        {
            CompletedLabel.Visible = false;
        }
        else

        {
            CompletedLabel.SetMarkup($"Completed: [color=green]{completedTime.ToString()}[/color]");
        }
        if (reward != null)
        {
            RewardLabel.TextRope = new Rope.Leaf(reward);
        }
        if (completedDesc != null)
        {
            CompletedDescriptionLabel.TextRope = new Rope.Leaf(completedDesc);
        }

    }
}
