using Content.Client.Message;
using Content.Shared.Cargo;
using Content.Shared.Cargo.Prototypes;
using Content.Shared.CCVar;
using Content.Shared.Random;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client.CrewAssignments.UI;

[GenerateTypedNameReferences]
public sealed partial class WorldObjectiveEntryFragment : BoxContainer
{
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    [Dependency] private readonly IConfigurationManager _cfgManager = default!;


    public WorldObjectiveEntryFragment(string title, string desc, string? reward = null, DateTime? completedTime = null, string? completedDesc = null)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        TitleLabel.Text = title;
        DescriptionLabel.SetMarkup(desc);
        if(completedTime == null)
        {
            CompletedLabel.Visible = false;
        }
        else

        {
            var yearOffset = _cfgManager.GetCVar(CCVars.YearOffset);
            var finalTime = completedTime.Value.AddYears(yearOffset);
            CompletedLabel.SetMarkup($"Completed: [color=green]{finalTime.ToString()}[/color]");
        }
        if(reward == null)
        { RewardLabel.Visible = false; }
        else
        {
            RewardLabel.SetMarkup(reward);
        }
        if (completedDesc == null)
        { CompletedDescriptionLabel.Visible = false; }
        else
        {
            CompletedDescriptionLabel.SetMarkup(completedDesc);
        }

    }
}
