using Content.Client.CrewAssignments.UI;
using Content.Shared.Access;
using Content.Shared.Access.Systems;
using Content.Shared.CCVar;
using Content.Shared.Invoices.Components;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Prototypes;
using System.Linq;
using static Content.Shared.GridControl.Components.GridConfigComponent;

namespace Content.Client.Invoices.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class InvoiceWindow : DefaultWindow
    {
        [Dependency] private readonly IConfigurationManager _cfgManager = default!;
        [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
        [Dependency] private readonly ILogManager _logManager = default!;
        private readonly ISawmill _logMill = default!;

        private readonly InvoiceBoundUserInterface _owner;

        public InvoiceWindow(InvoiceBoundUserInterface owner, IPrototypeManager prototypeManager)
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
            _logMill = _logManager.GetSawmill(SharedIdCardConsoleSystem.Sawmill);

            _owner = owner;
            PayButton.OnPressed += _ => PayInvoice();
            PossibleAccounts.OnItemSelected += OnTargetSelected;
        }
        private void OnTargetSelected(OptionButton.ItemSelectedEventArgs args)
        {
            PossibleAccounts.SelectId(args.Id);
        }
        public void UpdateState(InvoiceBoundUserInterfaceState state)
        {
            ReasonLabel.Text = state.InvoiceReason;
            CostLabel.Text = $"${state.InvoiceCost}";
            PaidToLabel.Text = state.PaidTo;
            if(state.Paid)
            {
                PossibleAccounts.Visible = false;
                PaidByLabel.Text = state.PaidBy;
                PaidByLabel.Visible = true;
                PaidLabel.Visible = true;
                PayButton.Visible = false;
            }
            else
            {
                PossibleAccounts.Visible = true;
                PaidByLabel.Visible = false;
                PaidLabel.Visible = false;
                PayButton.Visible = true;
                PossibleAccounts.Clear();
                PossibleAccounts.AddItem(state.UserName, 0);
                foreach (var account in state.PossibleStations)
                {
                    PossibleAccounts.AddItem(account.Value, account.Key);
                }
            }
        }

        public void PayInvoice()
        {
            if (PossibleAccounts.SelectedId == 0)
            {
                _owner.SendMessage(new PayInvoicePersonal());

            }
            else
            {
                _owner.SendMessage(new PayInvoice(PossibleAccounts.SelectedId));
            }
            Close();
        }

    }
}
