using Content.Client.CrewAssignments.UI;
using Content.Shared.Access;
using Content.Shared.Access.Systems;
using Content.Shared.CCVar;
using Content.Shared.Invoices.Components;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Prototypes;
using System.Linq;

namespace Content.Client.Invoices.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class InvoicePrinterConsoleWindow : DefaultWindow
    {
        [Dependency] private readonly IConfigurationManager _cfgManager = default!;
        [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
        [Dependency] private readonly ILogManager _logManager = default!;
        private readonly ISawmill _logMill = default!;

        private readonly InvoicePrinterConsoleBoundUserInterface _owner;

        public InvoicePrinterConsoleWindow(InvoicePrinterConsoleBoundUserInterface owner, IPrototypeManager prototypeManager)
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
            _logMill = _logManager.GetSawmill(SharedIdCardConsoleSystem.Sawmill);

            _owner = owner;

            PrintButton.OnPressed += _ => Print();

            ChangeModeBtn.OnPressed += _ => ChangeMode();


        }

        public void UpdateState(InvoicePrinterConsoleBoundUserInterfaceState state)
        {
            PrivilegedIdButton.Text = state.IdPresent
                ? Loc.GetString("id-card-console-window-eject-button")
                : Loc.GetString("id-card-console-window-insert-button");

            PrivilegedIdLabel.Text = state.IdName;
            if (state.StationMode)
            {
                ChangeModeBtn.Text = "Personal";
                TaxDetails.Visible = false;
            }
            else
            {
                ChangeModeBtn.Text = "Station";
                TaxDetails.Visible = true;
            }
            TargetAccountLabel.Text = state.TargetName;
            TaxRateLabel.Text = $"Sales Tax: {state.TaxRate}%";


        }
        public void Print()
        {
            var invoiceReason = ReasonLineEdit.Text;
            var invoiceCost = CostSpinBox.Value;
            if (invoiceCost < 1) return;
            _owner.SendMessage(new PrintInvoice(invoiceReason, invoiceCost));
            ReasonLineEdit.Text = "";
            CostSpinBox.Value = 0;
            Close();

        }
        public void ChangeMode()
        {
            _owner.SendMessage(new ChangeInvoiceMode());
        }

    }
}
