using Content.Client.CrewAssignments.UI;
using Content.Shared.Access;
using Content.Shared.Access.Systems;
using Content.Shared.CCVar;
using Content.Shared.Invoices.Components;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
using System.Linq;

namespace Content.Client.Invoices.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class InvoicePrinterConsoleWindow : DefaultWindow
    {
        [Dependency] private readonly IConfigurationManager _cfgManager = default!;
        [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
        [Dependency] private readonly ILogManager _logManager = default!;
        private readonly ISawmill _logMill = default!;

        private readonly InvoicePrinterConsoleBoundUserInterface _owner;

        public InvoicePrinterConsoleWindow(InvoicePrinterConsoleBoundUserInterface owner, IPrototypeManager prototypeManager)
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
            _logMill = _logManager.GetSawmill(SharedIdCardConsoleSystem.Sawmill);

            _owner = owner;

            PrintButton.OnPressed += _ => Print();

            ChangeModeStation.OnPressed += _ => ChangeMode();
            ChangeModePersonal.OnPressed += _ => ChangeMode();
            ChangeModePayslip.OnPressed += _ => ChangeModePay();
            ChangeModeInvoice.OnPressed += _ => ChangeModePay();

        }

        public void UpdateState(InvoicePrinterConsoleBoundUserInterfaceState state)
        {
            PrivilegedIdButton.Text = state.IdPresent
                ? Loc.GetString("id-card-console-window-eject-button")
                : Loc.GetString("id-card-console-window-insert-button");
            TaxDetails.Visible = true;
            if (state.IdName != null)
            {
                PrivilegedIdButton.Text = state.IdName;
            }
            ChangeModePayslip.Disabled = false;
            ChangeModeInvoice.Disabled = false;
            if (state.StationMode)
            {
                PossibleStations.Visible = true;
                if(state.SelectedStation != 0 && state.SelectedStation == state.TaxingStation)
                {
                    TaxDetails.Visible = false;
                }
                ChangeModeStation.Pressed = true;
                ChangeModePersonal.Pressed = false;
                TargetAccountLabel.Text = state.SelectedName;
                if(state.SelectedStation == 0)
                {
                    PrintButton.Disabled = true;
                }
                else
                {
                    PrintButton.Disabled = false;
                }
                if (state.InvoiceMode)
                {
                    ChangeModeInvoice.Pressed = true;
                    ChangeModePayslip.Pressed = false;
                    InvoiceModeLabel.Text = $"An invoice paid to {state.SelectedName} by the reciever.";
                    PrintButton.Text = "Print Invoice";
                }
                else
                {
                    ChangeModeInvoice.Pressed = false;
                    ChangeModePayslip.Pressed = true;
                    InvoiceModeLabel.Text = $"A payslip paid by {state.SelectedName} and deposited by the reciever.";
                    PrintButton.Text = "Pay & Print Payslip";
                }
            }
            else
            {
                InvoiceModeLabel.Text = $"An invoice paid to {state.TargetName} by the reciever.";
                ChangeModeInvoice.Pressed = true;
                ChangeModePayslip.Disabled = true;
                PossibleStations.Visible = false;
                ChangeModeStation.Pressed = false;
                ChangeModePersonal.Pressed = true;
                TargetAccountLabel.Text = state.TargetName;
                if(state.TargetName == null || state.TargetName == string.Empty)
                {
                    PrintButton.Disabled = true;
                }
                else
                {
                    PrintButton.Disabled = false;
                }
            }

            if(state.TaxRate < 1)
            {
                TaxDetails.Visible = false;
            }
            TaxingAccountLabel.Text = state.TaxingName;
            TaxRateLabel.Text = $"Sales Tax: {state.TaxRate}%";
            PossibleStations.Clear();
            PossibleStations.AddItem("Select Faction");
            foreach (var kv in state.FormattedStations)
            {
                PossibleStations.AddItem(kv.Value, kv.Key);
            }


        }
        public void Print()
        {
            var invoiceReason = Rope.Collapse(ReasonLineEdit.TextRope);
            var invoiceCost = CostSpinBox.Value;
            var invoiceTitle = InvoiceTitleLE.Text;
            if (invoiceCost < 1) return;
            _owner.SendMessage(new PrintInvoice(invoiceReason, invoiceCost, invoiceTitle));
            ReasonLineEdit.TextRope = new Rope.Leaf("");
            CostSpinBox.Value = 0;
            Close();

        }
        public void ChangeMode()
        {
            _owner.SendMessage(new ChangeInvoiceMode());
        }

        public void ChangeModePay()
        {
            _owner.SendMessage(new ChangeInvoicePayslipMode());
        }

    }
}
