using System.Linq;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Content.Client.Access.UI;
using Content.Client.Doors.Electronics;
using Content.Shared.Access;
using Content.Shared.Doors.Electronics;
using FancyWindow = Content.Client.UserInterface.Controls.FancyWindow;

namespace Content.Client.Doors.Electronics;

[GenerateTypedNameReferences]
public sealed partial class DoorElectronicsConfigurationMenu : FancyWindow
{
    private readonly AccessLevelControl _buttonsList = new();

    public event Action<List<ProtoId<AccessLevelPrototype>>>? OnAccessChanged;
    public event Action<string>? OnAccessToggle;
    public event Action<string>? PersonalAccessToggle;

    public DoorElectronicsConfigurationMenu()
    {
        RobustXamlLoader.Load(this);
    }

    public void Reset(IPrototypeManager protoManager, List<ProtoId<AccessLevelPrototype>> accessLevels)
    {
    }

    public void UpdateState(DoorElectronicsConfigurationState state)
    {
        AccessLevelControlContainer.RemoveAllChildren();
        PersonalAccessContainer.RemoveAllChildren();
        StationNameLabel.Text = state.StationName;
        if(state.PersonalAccess && state.PersonalAccessList != null)
        {
            ChangeMode.Text = "Station";
            PersonalAccessAddContainer.Visible = true;
            PersonalAccessContainer.Visible = true;
            AccessLevelControlContainer.Visible = false;
            foreach(var access in state.PersonalAccessList)
            {
                Button button = new();
                button.Text = access;
                PersonalAccessContainer.AddChild(button);
                button.OnPressed += _ => { PersonalAccessToggle?.Invoke(access); };
            }
            
        }
        else
        {
            ChangeMode.Text = "Personal";
            PersonalAccessAddContainer.Visible = false;
            PersonalAccessContainer.Visible = false;
            AccessLevelControlContainer.Visible = true;
            if (state.PossibleAccess != null)
            {
                foreach (var access in state.PossibleAccess)
                {
                    Button button = new();
                    button.Text = access;
                    AccessLevelControlContainer.AddChild(button);
                    button.OnPressed += _ => { OnAccessToggle?.Invoke(access); };
                    if (state.AccessList.Contains(access))
                    {
                        button.Pressed = true;
                    }
                }
            }
        }
    }
}
