using System.Linq;
using Content.Client.MCTN.BUI;
using Content.Shared.Atmos;
using Content.Shared.SensorMonitoring;
using Content.Shared.MCTN.BUIStates;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.MCTN.UI;

[GenerateTypedNameReferences]
public sealed partial class MCTNPipeStatusGrid : GridContainer
{

    public MCTNPipeStatusGrid(MCTNBoundUserInterface bui, MCTNPipePlugState plug, MCTNPlugCard parent)
    {
        RobustXamlLoader.Load(this);
        var localState = plug.LocalState.GasMix.ToPrettyString();
        var remoteState = plug.RemoteState.GasMix.ToPrettyString();

        foreach (var label in GetGasMixLabels(localState))
        {
            label.Align = Label.AlignMode.Right;
            LocalMix.AddChild(label);
        }
        foreach (var label in GetGasMixLabels(remoteState))
            RemoteMix.AddChild(label);

        LocalMoles.Text = parent.FormatValue(SensorUnit.Moles, localState.TotalMoles);
        RemoteMoles.Text = parent.FormatValue(SensorUnit.Moles, remoteState.TotalMoles);


        LocalPressure.Text = parent.FormatValue(SensorUnit.PressureKpa, localState.Pressure);
        RemotePressure.Text = parent.FormatValue(SensorUnit.PressureKpa, remoteState.Pressure);

        LocalTemperature.Text = parent.FormatValue(SensorUnit.TemperatureK, localState.Temperature);
        RemoteTemperature.Text = parent.FormatValue(SensorUnit.TemperatureK, remoteState.Temperature);
    }

    private static IEnumerable<string> PrettifyMix(GasMixtureStringRepresentation mix)
    {
        var gases = mix.MolesPerGas
            .OrderByDescending(x => x.Value)
            .Select(x => $"{x.Key} {(x.Value / mix.TotalMoles) * 100:F1}%")
            .ToArray();
        if (gases.Length > 3)
            return gases.Take(3).Append("...");
        return gases;
    }

    private static IEnumerable<Label> GetGasMixLabels(GasMixtureStringRepresentation mix)
    {
        foreach (var str in PrettifyMix(mix))
        {
            Label label = new()
            {
                Text = str,
                Modulate = Color.Cyan,
                HorizontalExpand = true,
                VerticalExpand = false
            };
            label.StyleClasses.Add("LabelSubText");
            yield return label;
        }
    }
}
