using Content.Client.MCTN.BUI;
using Content.Shared.MCTN.BUIStates;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.MCTN.UI;

[GenerateTypedNameReferences]
public sealed partial class MCTNAvailableConnectionRow : PanelContainer
{
    private MCTNAvailableConnection _conn;

    public MCTNAvailableConnectionRow(MCTNBoundUserInterface bui, MCTNAvailableConnection conn)
    {
        _conn = conn;
        RobustXamlLoader.Load(this);

        PlugName.Text = conn.Name;
        PlugDistance.Text = $"({conn.Distance:F1}m)";

        ConnectBtn.Disabled = conn.Occupied;
        if (conn.Occupied)
        {
            ConnectBtn.Text = "Occupied";
            ConnectBtn.Modulate = Color.Red;
        }
        ConnectBtn.OnPressed += (args) =>
        {
            if (bui == null) return;
            bui.SendMessage(new MCTNConnectMessage(conn.Entity));
        };
        // PlugOccupied.Text = conn.Occupied.ToString();
    }

}
