using Content.Client.MCTN.BUI;
using Content.Shared.SensorMonitoring;
using Content.Shared.MCTN.BUIStates;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.MCTN.UI;

[GenerateTypedNameReferences]
public sealed partial class MCTNPowerStatusGrid : GridContainer
{
    public MCTNPowerStatusGrid(MCTNBoundUserInterface bui, MCTNPowerPlugState plug, MCTNPlugCard parent)
    {
        RobustXamlLoader.Load(this);

        LocalLoad.Text = parent.FormatValue(SensorUnit.PowerW, plug.LocalState.CombinedLoad);
        RemoteLoad.Text = parent.FormatValue(SensorUnit.PowerW, plug.RemoteState.CombinedLoad);

        LocalSupply.Text = parent.FormatValue(SensorUnit.PowerW, plug.LocalState.CombinedSupply);
        RemoteSupply.Text = parent.FormatValue(SensorUnit.PowerW, plug.LocalState.CombinedSupply);

        LocalMaxSupply.Text = parent.FormatValue(SensorUnit.PowerW, plug.LocalState.CombinedMaxSupply);
        RemoteMaxSupply.Text = parent.FormatValue(SensorUnit.PowerW, plug.RemoteState.CombinedMaxSupply);

    }

}
