using Content.Client.UserInterface.Controls;
using Content.Shared.Cargo;
using Content.Shared.Cargo.BUI;
using Content.Shared.Radio.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Cargo.UI;

[GenerateTypedNameReferences]
public sealed partial class CargoPalletMenu : FancyWindow
{
    public Action? SellRequested;
    public Action? AppraiseRequested;
    public Action? ChangeMoneyMode;

    public CargoPalletMenu()
    {
        RobustXamlLoader.Load(this);
        SellButton.OnPressed += OnSellPressed;
        AppraiseButton.OnPressed += OnAppraisePressed;
        PaymentType.OnPressed += OnChangeMoneyMode;
        
    }

    

    public void SetAppraisal(int amount, int tax, CargoSaleMode moneyMode, string taxName)
    {
        float taxmult = (float)tax / 100f;
        var taxpaid = (float)amount * taxmult;
        amount -= (int)Math.Round(taxpaid);
        TaxPaidLabel.Text = $"${(int)Math.Round(taxpaid)}";
        TaxLabel.Text = $"{tax}% paid to {taxName}";

        if (moneyMode != CargoSaleMode.Deposit)
        {
            ConnectedBC.Visible = false;
        }
        else
        {
            ConnectedBC.Visible = true;
        }

            AppraisalLabel.Text = Loc.GetString("cargo-console-menu-points-amount", ("amount", amount.ToString()));
        
    }

    public void SetMoneyMode(CargoSaleMode CashEnabled)
    {
        if(CashEnabled == CargoSaleMode.Cash)
        {
            PaymentType.Text = "Cash (Spesos)";
        }
        else if (CashEnabled == CargoSaleMode.Deposit)
        {
            PaymentType.Text = "Direct to Station";
        }
        else
        {
            PaymentType.Text = "Payslip";
        }
        
    }
    public void SetCount(int count)
    {
        CountLabel.Text = count.ToString();
    }

    public void SetStation(string selectedName, int taxingStation, int selectedStation, Dictionary<int, string> stations, CargoSaleMode moneyMode)
    {
        
        if (moneyMode == CargoSaleMode.Deposit && taxingStation == selectedStation)
        {
            TaxContainer.Visible = false;
            TaxPaidContainer.Visible = false;
        }
        else
        {
            TaxContainer.Visible = true;
            TaxPaidContainer.Visible = true;
        }
        PossibleStations.Clear();
        PossibleStations.AddItem("Select Faction");
        foreach (var kv in stations)
        {
            PossibleStations.AddItem(kv.Value, kv.Key);
        }

        StationLabel.Text = selectedName;
    }
    public void SetEnabled(bool enabled)
    {
        AppraiseButton.Disabled = !enabled;
        SellButton.Disabled = !enabled;
    }

    private void OnSellPressed(BaseButton.ButtonEventArgs obj)
    {
        SellRequested?.Invoke();
    }

    private void OnAppraisePressed(BaseButton.ButtonEventArgs obj)
    {
        AppraiseRequested?.Invoke();
    }

    private void OnChangeMoneyMode(BaseButton.ButtonEventArgs obj)
    {
        ChangeMoneyMode?.Invoke();
    }
}
