using System.Linq;
using Content.Shared.Access;
using Content.Shared.Access.Systems;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using static Content.Shared.Access.Components.AccessOverriderComponent;

namespace Content.Client.Access.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class AccessOverriderWindow : DefaultWindow
    {
        public event Action<List<ProtoId<AccessLevelPrototype>>>? OnSubmit;
        public event Action<string>? OnAccessToggle;
        public event Action<string>? OnPersonalAccessToggle;

        public AccessOverriderWindow()
        {
            RobustXamlLoader.Load(this);
        }

        public void SetAccessLevels(IPrototypeManager protoManager, List<ProtoId<AccessLevelPrototype>> accessLevels)
        {
            AccessLevelGrid.RemoveAllChildren();

        }

        public void UpdateState(IPrototypeManager protoManager, AccessOverriderBoundUserInterfaceState state)
        {
            PrivilegedIdLabel.Text = state.PrivilegedIdName;
            PrivilegedIdButton.Text = state.IsPrivilegedIdPresent
                ? Loc.GetString("access-overrider-window-eject-button")
                : Loc.GetString("access-overrider-window-insert-button");

            TargetNameLabel.Text = state.TargetLabel;
            TargetNameLabel.FontColorOverride = state.TargetLabelColor;

            MissingPrivilegesLabel.Text = "";
            MissingPrivilegesLabel.FontColorOverride = Color.Yellow;

            MissingPrivilegesText.Text = "";
            MissingPrivilegesText.FontColorOverride = Color.Yellow;

            if (state.MissingAccessList != null && state.MissingAccessList.Any())
            {
                var missingPrivileges = new List<string>();

                foreach (string tag in state.MissingAccessList)
                {
                    missingPrivileges.Add(tag);
                }

                MissingPrivilegesLabel.Text = Loc.GetString("access-overrider-window-missing-privileges");
                MissingPrivilegesText.Text = string.Join(", ", missingPrivileges);
            }

            var interfaceEnabled = state.IsPrivilegedIdPresent && state.IsPrivilegedIdAuthorized;
            StationNameLabel.Text = state.StationName;
            AccessLevelGrid.RemoveAllChildren();
            PersonalAccessContainer.RemoveAllChildren();
            if(state.PersonalAccess)
            {
                AccessLevelGrid.Visible = false;
                ChangeMode.Text = "Station";
                PersonalAccessAddContainer.Visible = true;
                PersonalAccessContainer.Visible = true;
                if(state.PersonalAccessList != null)
                {
                    foreach (var access in state.PersonalAccessList)
                    {
                        Button button = new();
                        button.Text = access;
                        PersonalAccessContainer.AddChild(button);
                        if (interfaceEnabled)
                            button.OnPressed += _ => { OnPersonalAccessToggle?.Invoke(access); };
                        else
                            button.Disabled = true;

                    }
                }
            }
            else
            {
                AccessLevelGrid.Visible = true;
                PersonalAccessAddContainer.Visible = false;
                PersonalAccessContainer.Visible = false;
                ChangeMode.Text = "Personal";
                if (state.AllAccesses != null)
                {
                    foreach (var access in state.AllAccesses)
                    {
                        var newButton = new Button
                        {
                            Text = access,
                            ToggleMode = true,
                        };

                        AccessLevelGrid.AddChild(newButton);
                        if (!interfaceEnabled || (state.MissingAccessList != null && state.MissingAccessList.Contains(access)))
                        {
                            newButton.Disabled = true;
                        }
                        if (state.AccessList != null && state.AccessList.Contains(access))
                        {
                            newButton.Pressed = true;
                        }

                        newButton.OnPressed += _ =>
                        {
                            OnAccessToggle?.Invoke(access);
                        };

                    }
                }
            }
            
            
        }
    }
}
