using Content.Shared.Cargo;
using Content.Shared.Cargo.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Access.UI
{
    public sealed partial class AssignmentButton : Button
    {
        public int ID { get; set; }

        public AssignmentButton(int id, string name)
        {
            ID = id;
            Text = name;
        }
    }
}
