using Content.Client.CrewAssignments.UI;
using Content.Shared.Access;
using Content.Shared.Access.Systems;
using Content.Shared.CCVar;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Prototypes;
using System.Linq;
using static Content.Shared.Access.Components.IdCardConsoleComponent;

namespace Content.Client.Access.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class IdCardConsoleWindow : DefaultWindow
    {
        [Dependency] private readonly IConfigurationManager _cfgManager = default!;
        [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
        [Dependency] private readonly ILogManager _logManager = default!;
        private readonly ISawmill _logMill = default!;

        private readonly IdCardConsoleBoundUserInterface _owner;

        // CCVar.
        private int _maxNameLength;
        private int _maxIdJobLength;

        private readonly List<string> _jobPrototypeIds = new();

        private string? _lastFullName;
        private string? _lastJobTitle;
        private string? _lastJobProto;

        // The job that will be picked if the ID doesn't have a job on the station.
        private static ProtoId<JobPrototype> _defaultJob = "Passenger";

        public IdCardConsoleWindow(IdCardConsoleBoundUserInterface owner, IPrototypeManager prototypeManager,
            List<ProtoId<AccessLevelPrototype>> accessLevels)
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
            _logMill = _logManager.GetSawmill(SharedIdCardConsoleSystem.Sawmill);

            _owner = owner;

            _maxNameLength = _cfgManager.GetCVar(CCVars.MaxNameLength);
            _maxIdJobLength = _cfgManager.GetCVar(CCVars.MaxIdJobLength);

            FullNameLineEdit.OnTextEntered += _ => SubmitData();
            FullNameLineEdit.IsValid = s => s.Length <= _maxNameLength;
            FullNameLineEdit.OnTextChanged += _ =>
            {
                FullNameSaveButton.Disabled = FullNameSaveButton.Text == _lastFullName;
            };
            FullNameSaveButton.OnPressed += _ => SubmitData();

            JobTitleLineEdit.IsValid = s => s.Length <= _maxIdJobLength;

        }

        public void UpdateState(IdCardConsoleBoundUserInterfaceState state)
        {
            PrivilegedIdButton.Text = state.IsPrivilegedIdPresent
                ? Loc.GetString("id-card-console-window-eject-button")
                : Loc.GetString("id-card-console-window-insert-button");

            PrivilegedIdLabel.Text = state.PrivilegedIdName;

            TargetIdButton.Text = state.IsTargetIdPresent
                ? Loc.GetString("id-card-console-window-eject-button")
                : Loc.GetString("id-card-console-window-insert-button");

            TargetIdLabel.Text = state.TargetIdName;

            var interfaceEnabled =
                state.IsPrivilegedIdPresent && state.IsPrivilegedIdAuthorized && state.TargetIdFullName != null && state.TargetIdFullName != "";
            if (state.TargetIdFullName != null)
            {
                FullNameLineEdit.Text = state.TargetIdFullName;
                SelectedAccountLabel.Text = state.TargetIdFullName;
            }
            else
            {
                SelectedAccountLabel.Text = "*None*";
            }

                var fullNameDirty = _lastFullName != null && FullNameLineEdit.Text != state.TargetIdFullName;

            FullNameLabel.Modulate = interfaceEnabled ? Color.White : Color.Gray;
            if (!fullNameDirty)
            {
                FullNameLineEdit.Text = state.TargetIdFullName ?? string.Empty;
            }

            FullNameSaveButton.Disabled = !fullNameDirty;

            JobTitleLabel.Modulate = Color.Gray;
            JobTitleLineEdit.Editable = false;
            JobTitleLineEdit.Text = "*Unassigned*";
            if (state.Assignment != null) JobTitleLineEdit.Text = state.Assignment.Name;


            _lastFullName = state.TargetIdFullName;
            AccessLevelControlContainer.RemoveAllChildren();
            if (state.AllAssignments != null)
            {
                foreach (var item in state.AllAssignments)
                {
                    var id = item.Key;
                    var assignment = item.Value;
                    var button = new AssignmentButton(id, assignment.Name);
                    button.OnPressed += (args) => { _owner.OnAssignmentPressed(args); };
                    AccessLevelControlContainer.AddChild(button);
                    if(state.TargetIdFullName == null || state.TargetIdFullName.Length == 0 || (!state.IsOwner && state.PrivAssignment == null))
                    {
                        button.Disabled = true;
                    }
                    else
                    {

                        if(state.Assignment != null && state.Assignment.ID == id)
                        {
                            button.Pressed = true;
                        }
                        else if (!state.IsOwner && ((state.PrivAssignment == null) || assignment.Clevel >= state.PrivAssignment.Clevel || (state.Assignment != null && state.Assignment.Clevel >= state.PrivAssignment.Clevel)))
                        {
                            button.Disabled = true;
                        }
                    }
                }

            }
        }

        private void SubmitData()
        {
            _owner.SearchRecord(FullNameLineEdit.Text);
        }
    }
}
