using Content.Client.CrewAssignments.UI;
using Content.Shared.Access;
using Content.Shared.Access.Systems;
using Content.Shared.CCVar;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Prototypes;
using System.Linq;
using static Content.Shared.Access.Components.IdCardConsoleComponent;
using static Content.Shared.Access.Components.IdPrinterConsoleComponent;

namespace Content.Client.Access.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class IdPrinterConsoleWindow : DefaultWindow
    {
        [Dependency] private readonly IConfigurationManager _cfgManager = default!;
        [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
        [Dependency] private readonly ILogManager _logManager = default!;
        private readonly ISawmill _logMill = default!;

        private readonly IdPrinterConsoleBoundUserInterface _owner;

        public IdPrinterConsoleWindow(IdPrinterConsoleBoundUserInterface owner, IPrototypeManager prototypeManager)
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
            _logMill = _logManager.GetSawmill(SharedIdCardConsoleSystem.Sawmill);

            _owner = owner;

            PrintButton.OnPressed += _ => Print();
        }

        public void UpdateState(IdPrinterConsoleBoundUserInterfaceState state)
        {

        }

        public void Print()
        {
            _owner.Print();
            Close();
        }

    }
}
